# Generated by Django 4.2.20 on 2025-10-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='employee',
            name='qualifications',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
