# Generated by Django 4.2.20 on 2025-10-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_qualifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebankdetails',
            name='bank_passbook_number',
        ),
        migrations.RemoveField(
            model_name='employeecontactdetails',
            name='alternate_mobile_number',
        ),
        migrations.RemoveField(
            model_name='employeecontactdetails',
            name='temporary_address',
        ),
        migrations.AddField(
            model_name='employeebankdetails',
            name='bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to='documents/bank_passbooks/'),
        ),
        migrations.AddField(
            model_name='employeedocuments',
            name='aadhar_certificate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeedocuments',
            name='pan_certificate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
