# Generated by Django 4.2.20 on 2025-10-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employeebankdetails_bank_passbook_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocuments',
            name='aadhar_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhar/'),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='pan_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan/'),
        ),
    ]
