# Generated by Django 4.2.20 on 2025-10-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeedocuments_aadhar_certificate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualifications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
