# Generated by Django 4.2.20 on 2025-10-11 06:14

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_delete_qualification_alter_employee_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=employees.models.employee_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to=employees.models.bank_passbook_upload_path),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='aadhar_certificate',
            field=models.FileField(blank=True, null=True, upload_to=employees.models.aadhar_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='degree_certificate',
            field=models.FileField(blank=True, null=True, upload_to=employees.models.degree_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='joining_letter',
            field=models.FileField(blank=True, null=True, upload_to=employees.models.joining_letter_upload_path),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='pan_certificate',
            field=models.FileField(blank=True, null=True, upload_to=employees.models.pan_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='pg_certificate',
            field=models.FileField(blank=True, null=True, upload_to=employees.models.pg_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='phd_certificate',
            field=models.FileField(blank=True, null=True, upload_to=employees.models.phd_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='puc_certificate',
            field=models.FileField(blank=True, null=True, upload_to=employees.models.puc_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='employeedocuments',
            name='tenth_certificate',
            field=models.FileField(blank=True, null=True, upload_to=employees.models.tenth_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetails',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to=employees.models.experience_certificate_upload_path),
        ),
    ]
