# Generated by Django 4.2.20 on 2025-10-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_last_name_alter_employee_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontactdetails',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
